### ISSUE TITLE
Not all files are deployed to gh-pages branch

### ISSUE THREAD

**Issue by pacoita** [angular-schule/angular-cli-ghpages#100]
Steps to reproduce:

1. Brand new angular project (ng new my-app). Angular v9.1.3

2. Github Repos is existing and I can push the initial code (branch master)

3. Run `ng add angular-cli-ghpages` 

4. Run `ng deploy`  --> Build is successful as well as the Git deploy message.
    gh-pages branch is created, but only some files have been deployed.

Other files are missing:
main.xxx
polyfills.xxx
runtime.xxx

But are present in the dist folder.

Am I missing anything? I used in a previous project the package and it was working as expected.

**Comment by JohannesHoppe** [comment]
Can you show the affected repository?

**Comment by pacoita** [comment]
https://github.com/pacoita/href-test/tree/gh-pages

**Comment by JohannesHoppe** [comment]
I did:

```
git clone git@github.com:JohannesHoppe/href-test.git
cd href-test
npm i && ng add angular-cli-ghpages
ng deploy --base-href=/href-test/
```

All the files are there:
https://github.com/JohannesHoppe/href-test/tree/gh-pages

So I can't reproduce this!

**Comment by pacoita** [comment]
Ok, no Idea why it did not work on my side then. Thanks for trying.
