### ISSUE TITLE
Deploy Step works fine but CSS is not applied

### ISSUE THREAD

**Issue by sauconny** [angular-schule/angular-cli-ghpages#101]
I was able to deploy fine using the CLI command locally and the gh-pages site was loaded. I had to make some minor modifications to the `index.html` page to fix a weird MIME type issue and also the JS files returning a 404...however now the CSS stylesheet doesn't apply and there is no error that is returned from the console.

Any idea how to work around this?

**Comment by JohannesHoppe** [comment]
Please refer to the README again or this article: https://angular.schule/blog/2020-01-everything-github#4-a-first-deployment-to-github-pages

You must setup --base-href correctly! 🙂👍

**Comment by sauconny** [comment]
That's the exact command I ran....like I said. It's up and deployed and the HTML elements are rendered as well as the JavaScript functionality. It's just that the CSS styles aren't applied. And there are no errors in the console.

**Comment by JohannesHoppe** [comment]
Can you show us the source code and the exact command?

**Comment by sauconny** [comment]
The command I ran was `ng deploy --base-href=/{insert project name}/`. This repository is not private...however I am trying to do this in GitHub Entreprise. So I can't share the source code (I know which isn't helpful 😞), but it really is just a simple Angular project set up with the CLI using a UI framework.

**Comment by JohannesHoppe** [comment]
I'm pretty much sure this is not a bug on angular-cli-ghpages. And without any additional information, I can't help here, too.

**Comment by fmalcher** [comment]
When you do a normal build with `ng build --prod`, can you find the CSS bundle in the `dist` folder then, next to the other bundles?

**Comment by sauconny** [comment]
> When you do a normal build with `ng build --prod`, can you find the CSS bundle in the `dist` folder then, next to the other bundles?

Yep, `styles.{gibberish}.css` shows up within the `dist` folder with the correct CSS contents as well.

**Comment by fmalcher** [comment]
Can you please try to build a minimal reproduction of the problem?
Create a new public repo with a new Angular CLI project and see whether it works there. Then we can take a look!
