### ISSUE TITLE
Cant upload using angular-gh-pages

### ISSUE THREAD

**Issue by Gillardo** [angular-schule/angular-cli-ghpages#102]
I have updated my project to use an angular workspace and would like to deploy my demo application using angular-gh-pages. The repo is https://github.com/Gillardo/ngx-bootstrap-datetime-popup

I have created a command in package.json called gh-pages which executes the command ng deploy demo --no-silent but when i run it i get this error in the console. Its seems that the project has built successfully, but its failing on uploading it to git?

I am running this on windows 10 machine.

Can anyone help please?  I have added the details to this stackoverflow post
https://stackoverflow.com/questions/61117861/uploading-to-git-using-angular-gh-pages-git-upload-pack-git-upload-pack?noredirect=1#comment108836538_61117861

This is the error i am getting
![image](https://user-images.githubusercontent.com/7406381/80822809-652c8c00-8bd3-11ea-9115-68d524897d62.png)

I have setup my angular.json file like so
![image](https://user-images.githubusercontent.com/7406381/80822897-88efd200-8bd3-11ea-9103-7fecef17a2d2.png)

All details can be found at my repo.  Any help much appreciated

**Comment by JohannesHoppe** [comment]
This is a very strange error. The message states that a clean should be done, but angular-cli-ghpages is doing this by default. Did you found a solution meanwhile?

**Comment by Gillardo** [comment]
Yes i did with the help of someone on stackoverflow

https://stackoverflow.com/questions/61117861/uploading-to-git-using-angular-gh-pages-remote-url-mismatch?noredirect=1#comment108972532_61117861

**Comment by JohannesHoppe** [comment]
Ok, git was not installed correctly. Thanks for the link. This will help other people in the future.
