### ISSUE TITLE
Change was needed after doing the "Quick Start"

### ISSUE THREAD

**Issue by timohe** [angular-schule/angular-cli-ghpages#103]
When I followed your tutorial I had to do this additional change in the code after ng deploy. I am so not sure if it depends on the circumstances but would be nice to change it in the code or add it somewhere in the readme.

```
<base href="/">
Change to
<base href="./">
```

Found the solution here https://stackoverflow.com/a/59576343/5554656
After that it worked.

**Comment by fmalcher** [comment]
You most likely need to set the `--base-href` option for `ng deploy` that is described further down in the README. We will add a note about this to the quick start guide. 👍
