### ISSUE TITLE
[Question] Deploying with --optimization=false

### ISSUE THREAD

**Issue by fireflysemantics** [angular-schule/angular-cli-ghpages#106]
Hi,

I need to switch off minification because it breaks the app.  We can do this when running the production compile like this:

```
ng serve -o  --prod --optimization=false

```

Can we also run `ng deploy` with this option?  

It seems the other way would be to build the files with:

```
ng build --prod --optimization=false
```

And then run:

```
ng deploy --no-build
```

Thoughts?

**Comment by JohannesHoppe** [comment]
You could change that setting permanently in the angular.json?!

**Comment by fireflysemantics** [comment]
Oh - Is it that easy.  I'll give it a shot.  Thank you!!
