### ISSUE TITLE
Quick start guide isn't relevant (can't find resources)

### ISSUE THREAD

**Issue by alexverbitsky** [angular-schule/angular-cli-ghpages#108]
Steps to reproduce:
https://github.com/angular-schule/angular-cli-ghpages#-quick-start-local-development-

Repo settings:
![image](https://user-images.githubusercontent.com/34838543/86152666-37978c80-bb09-11ea-92b1-a4d2301470fa.png)

Github pages (dev console/network):
![image](https://user-images.githubusercontent.com/34838543/86152783-5a29a580-bb09-11ea-94fc-ada77d7f4e85.png)

Environment:
Angular CLI: 10.0.0
Node: 12.16.1
OS: darwin x64
angular-cli-ghpages: 0.6.2

**Comment by fmalcher** [comment]
You need to provide the `--base-href` option since your application runs in a subfolder, as described [here](https://github.com/angular-schule/angular-cli-ghpages#a-you-dont-want-to-use-a-custom-domain).
This does not mean that the quickstart guide is irrelevant.
AFAIK @JohannesHoppe has this on his list so that the GitHub Pages URL can be detected automatically.
For the meantime, what do you think about mentioning the `--base-href` option in the QS guide?

**Comment by alexverbitsky** [comment]
> You need to provide the --base-href option since your application runs in a subfolder

What do you mean by "runs in a subfolder"?

> This does not mean that the quickstart guide is irrelevant.

Sorry. I didn't mention to blame

> AFAIK @JohannesHoppe has this on his list so that the GitHub Pages URL can be detected automatically.
> For the meantime, what do you think about mentioning the `--base-href` option in the QS guide?

I think it would make the QS guide more exhaustive

**Comment by JohannesHoppe** [comment]
I always wonder why --base-href I'd forgotten so often. Now we've found that single place where it isn't mentioned. This should be updated, since --base-href is the option that 80% of the users want.

**Comment by alexverbitsky** [comment]
> I did always wonder why --base-href is forgotten so often. Now we've found that single place where it isn't mentioned. This should be updated, since --base-href is the option that 80% of the users want.

I'm not familiar with this project. And everyone don't have enough time to explore the whole documentation sometimes. So yes, "--base-href" was exactly what I **needed**.

**Comment by JohannesHoppe** [comment]
Sorry, this is not the way how open source works. I invested my whole free time to build that tool and to write that long documentation.

Now you are using that tool for free. It's fair enough if you take 5 minutes of your important time to read the full README. 👎

**Comment by fmalcher** [comment]
@alexverbitsky We added a note to the Quick Start Guide.

**Comment by alexverbitsky** [comment]
@fmalcher @JohannesHoppe thank you very much for spending your time
