### ISSUE TITLE
Bug: Have to enter ssh key passphrase multiple times

### ISSUE THREAD

**Issue by distinctdan** [angular-schule/angular-cli-ghpages#113]
The ssh key password isn't being cached when deploying, resulting in multiple prompts. This caused me to think that ghpages was broken and it took me a long time to figure out it was actually prompting multiple times. Here's the output: 
```
👨‍🚀 Uploading via git, please wait...
Enter passphrase for key '/Users/MyUser/.ssh/id_rsa': 
Enter passphrase for key '/Users/MyUser/.ssh/id_rsa': 
Enter passphrase for key '/Users/MyUser/.ssh/id_rsa': 
🚀 Successfully published via angular-cli-ghpages! Have a nice day!
```
`OSX` version `10.14.6`
`angular-cli-ghpages` version `0.6.2`

**Comment by JohannesHoppe** [comment]
This is by design, angular-cli-ghpages does not do any authentication stuff. It just clones a separate git repo and uses the remote from the current directory. If you do "git clone xxx" you should face the same issue every time. The best option would be to generally solve the login problem so that "git clone" works fine again.

**Comment by distinctdan** [comment]
Ok, I think I understand why it's happening, but regardless of the technical reasons, this is still a user experience bug because it acts broken. It really shouldn't prompt more than once for the ssh password. There has to be a way to accomplish that because other applications are able to use git without repeated prompts. At the bare minimum, at least something should be added to the docs or better yet in the console output itself to warn that this is normal behavior.

**Comment by fmalcher** [comment]
I agree with Johannes that this is not at all related to angular-cli-ghpages and must be solved on the OS side.
Under Mac/Linux you can run `ssh-add` so it adds all the SSH keys from your local machine and asks for their passphrase. You can then establish SSH connections without entering the passphrase again.
If you think we should add this to the FAQ, would you mind creating a PR for this? 🙂 @distinctdan

**Comment by distinctdan** [comment]
Hmm, I looked at the source, and I do see that you guys are just using the gh-pages package, so you're right, there isn't really anything that can be done in this project. It's not a big deal to me that it happens multiple times, it was just not knowing if it was accepting my password or not.

I'd be willing to update the FAQ, I'll do a PR.

**Comment by distinctdan** [comment]
I wasn't able to do a PR for the wiki, it looks like unfortunately you can't fork a wiki. However, I wrote up some verbiage if you guys want to add it:

```
## Why is it prompting multiple times for my SSH password/passphrase?

Don't worry, this is normal behavior on unix systems if you have a password on your ssh key. `angular-cli-ghpages` uses the `gh-pages` package under the hood, which does multiple git operations. You can avoid these prompts by configuring an ssh agent.
```

**Comment by fmalcher** [comment]
> you guys are just using the gh-pages package

You're right! 🙂 However, this package is also just a wrapper around git commands. Git itself does not bother about SSH authentication at all, this mechanism is completely up to the SSH agent. Thus, also `gh-pages` couldn't change anything here. https://github.com/tschaub/gh-pages/blob/main/lib/git.js#L189

Thank you for the FAQ part! @JohannesHoppe Does this look fine from your side?

**Comment by JohannesHoppe** [comment]
Many thanks for the help. 👍 I added an entry to the FAQ:

https://github.com/angular-schule/angular-cli-ghpages/wiki/FAQ
