### ISSUE TITLE
Can't deploy angular project to the github re

### ISSUE THREAD

**Issue by VeeRHunter** [angular-schule/angular-cli-ghpages#116]
![image](https://user-images.githubusercontent.com/30534578/95760727-f6a13d80-0cdd-11eb-9a84-7d2c04f69e5d.png)

I can't deploy my angular project to the github pages by this issue.
Please help me.

**Comment by JohannesHoppe** [comment]
Run without silent option for details!

**Comment by VeeRHunter** [comment]
Is it possible to get detail cli?
For example ng deploy ... please...

**Comment by VeeRHunter** [comment]
> Run without silent option for details!

Is it possible to get detail cli?
For example ng deploy ... please...
