### ISSUE TITLE
docs: we are missing a full description of --buildTarget

### ISSUE THREAD

**Issue by alvachien** [angular-schule/angular-cli-ghpages#123]
Facing the following issue when trying to use "ng deploy":
❌ An error occurred when trying to deploy:
Invalid target string: "github"

Firstly, you can figure out the angular.json from my project: https://github.com/alvachien/knowledgebuilder/blob/master/angular.json

The configuration 'github' already defined, and "ng build -c github" works as expected.
The angular.json also including the options defined "angular-cli-ghpages".

Secondly, no matter run "ng deploy --configuration=github" or "ng deploy --build-target=github" results in same issue.

Could you give me a hint to make it work?

Now I using a workaround by a own NPM script: "deploy-github": "ng build -c github && git push origin :gh-pages && git subtree push --prefix dist origin gh-pages"

**Comment by JohannesHoppe** [comment]
Looks like the issue was already fixed.

**Comment by lukad03** [comment]
Can you point to how this was resolved @JohannesHoppe? I'm seeing the same issue still and even seeing it when `--build-target` is set to `production` and `prod`.

**Comment by JohannesHoppe** [comment]
@lukad03 Could you please provide the exact executed command and you `angular.json`?

**Comment by lukad03** [comment]
@JohannesHoppe Sure! https://github.com/XDgov/ML-Bias-Website/blob/lk-staging/angular.json

I actually got the script to work by specifying `--build-target=app-name:build:staging`

**Comment by JohannesHoppe** [comment]
@lukad03 I agree, everybody is confused by this. See https://github.com/angular/angularfire/pull/2281#issuecomment-605630403 😇 

Could you do me (and the project) a big favour and figure out which command does work and which does not?

* `ng deploy`
* `ng deploy --build-target=production`
* `ng deploy --build-target=staging`
* `ng deploy --build-target=bias-in-ai:build`
* `ng deploy --build-target=bias-in-ai:build:staging`
* `ng deploy --build-target=bias-in-ai:build:production`

Bonus points: A PR with an updated README.md 👍

**Comment by JohannesHoppe** [comment]
This is now documented in the README.
