### ISSUE TITLE
Cannot read property 'Workspace' of undefined

### ISSUE THREAD

**Issue by JonAlco** [angular-schule/angular-cli-ghpages#124]
Facing the following issue when trying to use "ng deploy":

❌ An error occurred when trying to deploy:
Cannot read property 'Workspace' of undefined

Firstly, you can figure out the angular.json from my project: 
[https://github.com/jalcocerzamora/app-manhattan-client/blob/master/angular.json](url)

**Comment by JohannesHoppe** [comment]
Could you try to upgrade Angular to a newer version? Does that help?

**Comment by JonAlco** [comment]
I have currently:
Angular CLI: 11.0.2
Node: 14.15.1

**Comment by JonAlco** [comment]
> Could you try to upgrade Angular to a newer version? Does that help?

I have currently:
Angular CLI: 11.0.2
Node: 14.15.1

**Comment by fmalcher** [comment]
In your package.json the Angular dependencies are still on v9. By running "ng update" you can lift the project to v11.

**Comment by JonAlco** [comment]
> In your package.json the Angular dependencies are still on v9. By running "ng update" you can lift the project to v11.

Okay, I executed "ng update" but It threw at the same issue.

[https://github.com/jalcocerzamora/app-manhattan-client/blob/master/angular.json](url)

[https://github.com/jalcocerzamora/app-manhattan-client/blob/master/package.json](url)

**Comment by fmalcher** [comment]
Okay, then your workspace might be corrupted. This has nothing to do with this module then.
You could try to generate a fresh new Angular project with "ng new" and copy your code into that new project.

Closing this for now!
