### ISSUE TITLE
Unable to run Page Speed (or Lighthouse) due to initial 404 error.

### ISSUE THREAD

**Issue by harvanchik** [angular-schule/angular-cli-ghpages#127]
Is there any way to run a page speed test?  Using angular-cli-ghpages, when the page loads, there is an initial 404 error thrown in the console, and the Page Speed errors out (see below).

![image](https://user-images.githubusercontent.com/66141166/115161636-b8515600-a053-11eb-8c7d-cc8d09fdc893.png)
![image](https://user-images.githubusercontent.com/66141166/115161669-d9b24200-a053-11eb-840e-c6cb3af1251f.png)

**Comment by JohannesHoppe** [comment]
Yes and no. You can make multiple copies of the index.html, for all tested routes. But only the workaround with the 404 page works for unknown routes.

**Comment by JohannesHoppe** [comment]
This is a limitation of GitHub Pages.

**Comment by harvanchik** [comment]
That's even tougher with dynamic routes like I have.  Bummer.
