### ISSUE TITLE
404 error when loading images

### ISSUE THREAD

**Issue by OSA413** [angular-schule/angular-cli-ghpages#128]
So, as the title says, I get 404 error when loading images/other resourses from the "assets" folder.
All links miss repo_name in their urls, like `https://mixtern.github.io/assets/images/logo.png` instead of `https://mixtern.github.io/app-store-parser-frontend/assets/images/logo.png` when the url in the code is `"./../../assets/images/logo.png"`

repo: https://github.com/mixtern/app-store-parser-frontend/
gh-pages: https://mixtern.github.io/app-store-parser-frontend/

These are the command that I've tried to use but they didn't work:
`ng deploy --base-href=https://mixtern.github.io/app-store-parser-frontend/`
`ng deploy --base-href=/app-store-parser-frontend/`
`ng deploy --base-href=\"./\"`

How can I fix this issue besides manually changing urls in the js file?

```
> ng --version
Angular CLI: 11.2.9
Node: 14.16.0
OS: win32 x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
rxjs                            6.6.7
typescript                      4.1.5
```

**Comment by OSA413** [comment]
So at this moment I just wrote a script that replaces `./../../assets/` with `./../../[repo-name]/assets/` in all `js` and `js.map` files and used it in the deploy script like this: 
```
"deploy": "ng build --prod --base-href=https://[user-name].github.io/[repo]/ && node .\\fix-gh-pages-urls.js && ng deploy --no-build"
```

**Comment by OSA413** [comment]
Alright, turns out that I have not to use relative path when accessing `assets` folder.
https://stackoverflow.com/questions/50400662/is-there-a-way-to-use-angular-base-href-as-variable-in-image-path

Closing this issue.

**Comment by fmalcher** [comment]
Haha, just read through your issue and stumbled upon your relative assets path. Yes, that should be the solution! 🙂

**Comment by OSA413** [comment]
It's funny that I ran into the same issue when I was working with React and using their module for gh-pages.
