### ISSUE TITLE
Support Angular v12

### ISSUE THREAD

**Issue by EdricChan03** [angular-schule/angular-cli-ghpages#131]
See https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49 for more info

**Comment by JohannesHoppe** [comment]
I will make a new version soonish. But there should be no breaking changes for us. `--force` should do the trick

**Comment by litwin90** [comment]
Hello everyone, when I try to add schematic to new cli I get the next warning:
**"angular-cli-ghpages-ng-add-schematic" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.**

Then when I try to deploy (by running **ng deploy --base-href=/<repositoryname>/**) I get a warning and an error:  
warning:   
**"Schema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.**  
error:   
**❌ An error occurred when trying to deploy:
Cannot read property 'Workspace' of undefined**  

And there is no additional information with --no-silent flag.
 
Angular CLI: 12.0.0
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

I haven't found any information that anybody faced the same issue, so I could suggest that it is a problem with migration to new Angular Cli

**Comment by JohannesHoppe** [comment]
@dianjuar have you ever seen this?! o_O

**Comment by dianjuar** [comment]
> @dianjuar have you ever seen this?! o_O

@JohannesHoppe 
I haven't taken the time to test V12 but I'm getting the same error

![image](https://user-images.githubusercontent.com/7026066/119038780-60ff1800-b968-11eb-883d-dbe8ab83a809.png)

Commands used
`ng add ngx-deploy-npm`
`ng deploy angular-lib`

**Comment by dianjuar** [comment]
@JohannesHoppe I got it.
You can see what needs to be changed here -> https://github.com/bikecoders/ngx-deploy-npm/pull/63

I'm not merging it because I need to perform some tests related to the builder itself (deprecation of view engine and some Nx concerns). Remember that it's related to libraries. 

I think those are all the changes that you need to support V12.

**Comment by dianjuar** [comment]
You are not the only one
https://github.com/ngneat/tailwind/issues/106

**Comment by JohannesHoppe** [comment]
Great work. 👍 
I have a computer-free weekend right now. But next week I'll apply your changes immediately. 😃

**Comment by JohannesHoppe** [comment]
@dianjuar Did you also find the time to check if this change causes problems with older Angular versions?

**Comment by dianjuar** [comment]
> @dianjuar Did you also found the time to check if this change causes problems with older Angular versions?

All good on Angular 12, 11, 10 and 9
