### ISSUE TITLE
Filename Too Long Error on ng deploy

### ISSUE THREAD

**Issue by MichaelKintscher** [angular-schule/angular-cli-ghpages#133]
I am getting "Filename too long" errors when attempting to deploy to GitHubt pages using `ng deploy --base-href=michaelkintscher.github.io --no-silent`:

![image](https://user-images.githubusercontent.com/17364071/120090177-48ec6e80-c0b5-11eb-92d9-818f100bba8f.png)

When I try the steps suggested in the error message, I get this:

![image](https://user-images.githubusercontent.com/17364071/120090198-75a08600-c0b5-11eb-9409-921e7f0ede8b.png)

I am on Windows 10, and used the Angular CLI to create my Angular workspace and project. The project repository is connected to GitHub already... I am not sure why this is cloning again.

**Comment by JohannesHoppe** [comment]
There's nothing we can do about it. To be able to push something via git, one must first clone the repo. This happens in a secret directory under node_modules. Under Windows, you have no other option than to minimise the directory length. Under Linux, Unix, Mac there is no such limitation.

**Comment by JohannesHoppe** [comment]
Theoretically, we could of course use the current git repo. But that would cause a lot more problems, so we might have to change the branch and stash your work results. Besides, you can also use angular-cli-ghpages if you don’t use version management or if you want to push to another repo.
