### ISSUE TITLE
ng add leads to error with Angular 13

### ISSUE THREAD

**Issue by fmalcher** [angular-schule/angular-cli-ghpages#138]
```
$ ng add angular-cli-ghpages@1.0.0-rc.2
Could not parse angular.json: Cannot read property 'Loose' of undefined
```

The reason is this line: https://github.com/angular-schule/angular-cli-ghpages/blob/master/src/ng-add.ts#L21

The JSON parser is deprecated. See https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/json/parser.ts#L926

**Comment by JohannesHoppe** [comment]
I just published `angular-cli-ghpages@1.0.0-rc.3` to npm! This version supports Angular 13.
Many thanks for the patch!
