### ISSUE TITLE
Deploy not working with Angular 13

### ISSUE THREAD

**Issue by willJOIN** [angular-schule/angular-cli-ghpages#142]
Hi, me and some colleagues are trying to deploy some Angular projects, and we saw that recently there has been issues between this package and Angular 13 and that they were fixed, but it turns out that now we have another problem. Everytime we deploy, the GitHub Pages deployment gets blank or only displays our README.md. We have tried building and deploying to a separate gh-pages branch, separate folder like dist or docs, and even on a new project. The title of the aplication works atleast. 

Some repos with the problem: 

https://github.com/willJOIN/Landing_Page_Angular

https://github.com/willJOIN/Clone_Google_Angular

**Comment by JohannesHoppe** [comment]
Please use the latest version, by updating the version in the `package.json` to 1.0.0 and running `npm install` afterwards.

The issue Is fixed here https://github.com/angular-schule/angular-cli-ghpages/issues/137

If the error still exists after the update, then please post a the error message here.

**Comment by willJOIN** [comment]
> 

Still doesn't work. This is not the same issue as before, and there's no error message either.

**Comment by JohannesHoppe** [comment]
Have you tried the `--no-silent` (https://github.com/angular-schule/angular-cli-ghpages#no-silent) parameter?

**Comment by willJOIN** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/83835899/143020489-0e4b337d-9d4c-4bf6-9629-8df68fcc23ce.png)

Still no error messages...

**Comment by JohannesHoppe** [comment]
The gh-pages branch is never reaching the remote, but there is also no error. This is strange...

Looks like you renamed the repo from `Landing_Page_Prototype` to `Landing_Page_Angular`.
Please try out a fresh clone of the repo. Right now it pushes to a remote which has a redirect. This might be the reason.

Hint: You will also have to set `--base-href=/landing_page_angular` if you plan to host the page on https://willjoin.github.io/landing_page_angular/ later on.

**Comment by willJOIN** [comment]
It didn't work, but maybe this is the error message. It always appears even after a fresh clone or deletion of node_modules folder.
Do you perhaps know what it means? Maybe something to do with the angular.json file?
![image](https://user-images.githubusercontent.com/83835899/143082842-d379010d-61ae-4660-bc0c-4dd718f8a666.png)

**Comment by willJOIN** [comment]
Yes, that's the problem, i created a new repo and without that error, it worked. Sorry for the trouble haha
