### ISSUE TITLE
Deployment command deletes files inside .idea folder

### ISSUE THREAD

**Issue by bharathkumarchowdary** [angular-schule/angular-cli-ghpages#144]
When using angular-cli-ghpages for deploying to GitHub Pages with this command
`npx angular-cli-ghpages --dir=dist/engg-calc/ --branch=gh-pages`
the following files from .idea folder which is a configuration storage folder for IntelliJ IDEA IDEs like WebStorm etc, are getting deleted
![0915E484-C127-4A23-84B2-F906E958230C_4_5005_c](https://user-images.githubusercontent.com/8872935/150667733-743c596c-9549-4146-a77e-65b7f1e8cbfa.jpeg)

**Comment by JohannesHoppe** [comment]
Take a look at the following option: https://github.com/angular-schule/angular-cli-ghpages#no-dotfiles

**Comment by JohannesHoppe** [comment]
There is a .gitignore file in that folder, are you sure that the folder isn't ignored by configuration?

**Comment by bharathkumarchowdary** [comment]
I was running this command for deploying while the gh-pages branch was checked out
`npx angular-cli-ghpages --dir=dist/engg-calc/ --branch=gh-pages`

realised if I run that command while on any other branch(master), the deletion of .idea folder files is not happening. Those files were untouched

I'm sure that if I run the above command while being on gh-pages branch, it will definitely delete all source code and also files of .idea

**Comment by JohannesHoppe** [comment]
I have no idea how to reproduce this issue. Feel free to reopen this issue if you have a demo to reproduce the problem.
