### ISSUE TITLE
Deploy command fails in an Nx repo

### ISSUE THREAD

**Issue by batbrain9392** [angular-schule/angular-cli-ghpages#145]
Reproduction steps:
1. Create an Nx repo
2. `npm i angular-cli-ghpages -D && npx nx g angular-cli-ghpages:ng-add`
3. `npx nx deploy`

Error: `Property 'cname' does not match the schema. 'false' should be a 'string'.`

Repo: [https://github.com/batbrain9392/ng-media-utils/tree/setup-gh-pages](https://github.com/batbrain9392/ng-media-utils/tree/setup-gh-pages)

**Comment by batbrain9392** [comment]
Solved it by adding `cname` flag manually as `github.com` along with `base-href`.

**Comment by batbrain9392** [comment]
However, `npx nx deploy` didn't work in Github Actions. I suppose I'll have to use a dedicated action like [GitHub Pages action](https://github.com/marketplace/actions/github-pages-action).

**Comment by JohannesHoppe** [comment]
I'm going to track the wrong default value for `cname` in a separate issue: https://github.com/angular-schule/angular-cli-ghpages/issues/154

**Comment by dianjuar** [comment]
In my experience, making a schematic run in an Nx Workspace is tricky and hacky. You have constantly made changes (maintenance) to have it running without problems.

On the other hand, it is considerably a lot simpler to run an Nx Plugin in an Angular Workspace.

What I would suggest to solve this problem is to migrate the project to a NxPlugin. It will be THE refactor, but I believe it is a good thing if we consider the long term.

I made that jump on [ngx-deploy-npm](https://github.com/bikecoders/ngx-deploy-npm/pull/77), and it has paid off. The DX (Development Experience) is sky levels of satisfaction. Also, allowing the project to not only cover Angular projects but the opportunity to support a lot more technologies is encouraging.

**Comment by JohannesHoppe** [comment]
Your PR:
<img width="242" alt="Screenshot 2022-11-09 at 18 53 54" src="https://user-images.githubusercontent.com/640639/200904357-14062986-ffb4-4d28-9dad-a59654c321c8.png">

So many great plans, so little time in life!

**Comment by dianjuar** [comment]
Some of the files are autogenerated, but it's still a long path.

Here is another project that migrated to be an Nx Plugin with 321 files https://github.com/ngworker/lumberjack/pull/136

**Comment by dianjuar** [comment]
The most satisfying thing is the ability to reach other technologies with almost no changes. `ngx-deploy-npm` went to support only Angular libraries to support a broader set of technologies.

https://github.com/bikecoders/ngx-deploy-npm#supported-library-generators
![image](https://user-images.githubusercontent.com/7026066/201282477-65a09a3c-32d0-4149-9eee-438355e8a37a.png)

`angular-cli-ghpages` could deploy React Apps and Next Apps. I guess the change would be so significant that the name needs to change too 🤣🤣🤣🤣

**Comment by dianjuar** [comment]
I just remembered that I had to share this.

I no longer share the vision of using an Nx Plugin on an Angular Workspace. In January 2024, I dropped support for Angular Workspace on one of my Nx Plugins. To support Nx and Angular workspaces without major problems, you must have two different packages, and from the maintainer's standpoint, it is just too much work.

I share more in detail this thought on a [blog post](https://dev.to/dianjuar/whats-coming-to-ngx-deploy-npm-v8-23gn)

> ## Drop support for Angular workspaces 🅰️
> The Angular workspace support started to be a load for the maintainers. Several times, the compatibility bridge Nx Devkit offered began to crumble until [it didn't work anymore](https://github.com/bikecoders/ngx-deploy-npm/issues/467).
> 
> The Nx ecosystem has continued evolving, and some of the original designs don't quite fit nowadays in Nx, but they do on Angular workspaces. That difference between both ecosystems makes us understand that to continue offering support for Angular workspaces, we must create and maintain two packages with separate approaches that benefit each workspace.
> 
> We have learned in these four years about maintaining packages that the work of a maintainer is hard. Maintaining two different NPM Packages would require considerable effort. We decided to focus on what brings the most value to our current users, and Nx Workspaces is the best way to do that.

**Comment by lppedd** [comment]
To clarify, is anyone here running this project on a Nx repo?
