### ISSUE TITLE
Move changelog to separate file

### ISSUE THREAD

**Issue by fmalcher** [angular-schule/angular-cli-ghpages#150]
The changelog should not be that present at the top of the README. This section can feature the latest highlights, but the full changelog should be moved to a separate CHANGELOG.md file.

**Comment by JohannesHoppe** [comment]
I agree, the README is pretty long. Right now I use the releases to document all changes:
https://github.com/angular-schule/angular-cli-ghpages/releases

Do you still think a CHANGELOG file is necessary?

**Comment by fmalcher** [comment]
Nope, the releases section is fine for me. However, the stuff at the top of the README has to go away.

**Comment by JohannesHoppe** [comment]
Fixed, README points to https://github.com/angular-schule/angular-cli-ghpages/releases now!
