### ISSUE TITLE
404.html is not copied when using angular localize

### ISSUE THREAD

**Issue by osamaz26** [angular-schule/angular-cli-ghpages#151]
I'm trying to deploy the project that has locales but I got the message "index.html could not be copied to 404.html. This does not look like an angular-cli project?!". I did a debug and found that the lib searches for the index.html in the route folder which is in my case dist but the build command creates 2 folders inside the dist folder. Each one of them has a locale. 

More info
Angular version:  14.0.0
angular-cli-ghpages: 1.0.0

**Comment by JohannesHoppe** [comment]
It should use the directory set is set up for that project in the angular.json. Could you provide a minimal demo so that we can try to reproduce this error?
