### ISSUE TITLE
build: Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by tutkli** [angular-schule/angular-cli-ghpages#157]
Executing pages-build-deployment action throws the warning:

> Build
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

**Comment by fmalcher** [comment]
Thanks for the report! The error has nothing to do with this library. Instead, you need to update your GitHub Actions pipeline to Node 16 as the error message suggests. 🙂
