### ISSUE TITLE
Angular v15 support

### ISSUE THREAD

**Issue by EdricChan03** [angular-schule/angular-cli-ghpages#158]
[Angular v15 was recently released](https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8). Are there plans to add Angular v15 support?

**Comment by JohannesHoppe** [comment]
Thank you for pointing this out. There are no breaking changes. I will quickly create a new release today.

**Comment by EdricChan03** [comment]
Thanks for the quick response! I've just attempted to update to 1.0.4 and I've noticed that it still produces a peer dependencies error:

```
❯ npm i angular-cli-ghpages@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: <project>@<version>
npm ERR! Found: @angular-devkit/architect@0.1500.0
npm ERR! node_modules/@angular-devkit/architect
npm ERR!   dev @angular-devkit/architect@"^0.1500.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular-devkit/architect@">= 0.900 < 0.1500" from angular-cli-ghpages@1.0.4
npm ERR! node_modules/angular-cli-ghpages
npm ERR!   dev angular-cli-ghpages@"1.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Looking at the [commit that added Angular v15 support shows that the version range for `@angular-devkit/architect` wasn't bumped as well](https://github.com/angular-schule/angular-cli-ghpages/commit/3494f5b4c6a9902988c2b9319ec7eabeaabdb900#diff-cc5a2f170768969f124108ad3be7fdbcbed774c11774d99a87a3a78fef4ab97bL74).

**Comment by JohannesHoppe** [comment]
🙏 here is the new relase: https://github.com/angular-schule/angular-cli-ghpages/releases/tag/v1.0.5

**Comment by mammadkoma** [comment]
I created a new repository in github
ng add Angular15
cd Angular15
git init
git remote add origin https://github.com/mammadkoma/Angular15.git
ng add angular-cli-ghpages
ng deploy --repo=https://github.com/mammadkoma/Angular15.git

It shows this message : 🌟 Successfully published via angular-cli-ghpages! Have a nice day!
but it doesn't work in my github pages: https://mammadkoma.github.io/Angular15/

**Comment by fmalcher** [comment]
@mammadkoma In your case, the deployment worked fine, so your problem doesn't seem to be related to the library.
If you want to deploy to a subfolder, you need to use the `--base-href` option as described here: https://github.com/angular-schule/angular-cli-ghpages#--base-href-

**Comment by mammadkoma** [comment]
I don't want to deploy to a subfolder.

**Comment by JohannesHoppe** [comment]
The tool is working as expected. This is not a support channel for individual projects.

**Comment by mammadkoma** [comment]
This is not individual project , it is created only by **ng new angular15** command like your npm documents. Please create a new angular 15 project and deploy to your github. If it works show us the steps. Thank you

**Comment by EdricChan03** [comment]
@mammadkoma I've taken a look at [your GitHub repository](https://github.com/mammadkoma/Angular15) and have discovered a potential cause of the issue: your repository is named as "**A**ngular15" (notice the capitalisation), but you've configured your `--base-href` to use "**a**ngular15".

Attempting to visit https://mammadkoma.github.io/Angular15/ does yield the HTML as expected, but the site breaks with 404 errors due to the issue mentioned above:

![Screenshot of Firefox DevTools Console showing 404 errors on the Angular15 subpage](https://user-images.githubusercontent.com/20047125/204466536-d4b4d82b-2d26-4b29-950f-ef07068ea468.jpg)

Hope this helps!

**Comment by mammadkoma** [comment]
Finally worked Thanks
![image](https://user-images.githubusercontent.com/17564001/204469989-c03a6e0e-f6b8-486c-a8f7-55fabbb3a996.png)
