### ISSUE TITLE
ng deploy ---- How to switch GitHub account by using ng deploy by angular-cli-ghpages?

### ISSUE THREAD

**Issue by seth1070223** [angular-schule/angular-cli-ghpages#161]
Hi, I successfully ng deploy my project to GitHub. Thank you.
Now I need to ng deploy to my another GitHub account.
Under terminal, I switch my Github account by 
git config credential.username "account2"
git config user.email "account2@gmail.com"
Then I can git push account2 master, successfully.
But when I 
ng deploy --repo=https://github.com/account2/reponame.git --no-silent --name="account2" --email="account2@gmail.com" --base-href="reponame"
It runs and get error
Permission deny to account2 by account1_username

How can I switch git account using ng deploy by angular-cli-ghpages?

Thank you.

**Comment by JohannesHoppe** [comment]
Try out personal access tokens (GH_TOKEN), this will work.

**Comment by seth1070223** [comment]
@JohannesHoppe 
Hi, Thanks for reply.
I am not sure what you said use GH_TOKEN.
In git cli to do git push  -u account**1** master, it will prompt to ask to enter account**1** username and password.
The password is personal access token.
Then the username and password is stored in this terminal environment.
Then do ng deploy, it will update successfully to git account**1**.

But now I want do switch account by git credential.username "account**2**"
When I go git push -u account**2** master, it can update to account**2**.
Then I do ng deploy  and suppose to update to account**2**, it got error saying
"Permission to account**2**/repo.git denied to account**1**."

I use MacBook Pro.
I tried to delete my keychain secret accessing GitHub and suppose the terminal ask me to enter account2 and password, it didn't ask me to do so. The account**1**'s username and token is still stored in terminal environment. I still can git push -u account**1** master successfully and ng deploy to account**1** successfully.

I tried again
git credential.username "account**2**"
then
ng deploy --repo=https://github.com/account**2**/reponame.git --no-silent --name="account**2**" --email="account**2**@gmail.com" --base-href="reponame" --GH-TOKEN=tokenkey 
the terminal reply
Error: Unknown argument: GH-TOKEN

Thanks for helping, what can I go to switch GitHub account when using ng deploy by angular-cli-ghpages?

Thank you very much.

**Comment by JohannesHoppe** [comment]
Please read this first: https://angular.schule/blog/2020-01-everything-github

**Comment by seth1070223** [comment]
@JohannesHoppe
Hi, Thanks for reply.
After your reply 3 weeks ago, I tried a lot of times to go through by your page above.
You suggest use CD/CI action script to deploy.
That did work.
But, for me, it gave me more homeworks.
I got lots of errors. Lots of errors about build, versions, errors...A LOT!
Thank you very much.

I am not very familiar with all these new techniques. It gets new every day.
Here, I found easy way for me.

I use MacBook, the terminal will catch the account of GitHub. This is the key point, key problem.
1. git config credential.username "Account1"
2. goto GitHub to generate personal token.
3. in terminal, git push repo1 master, then input the token form Account1
4. ng deploy --repo=https://github.com/Account1/repo1.git --base-href=/repo1/ --no-silent
5. then you get success for deploy to Account1
*6. then, DELETE token from Account1 in GitHub
7. then, in terminal, git config credential.username "Account2"
8. then, goto GitHub to generate token for Account2.
9.  in terminal, get push repo2 master, then input token from Account2.
10. then, ng deploy --repo=https://github.com/Account2/repo2.git --base-href=/repo2/ --no-silent
11. At this step maybe you will see error saying using Account1, please check you have delete token from Account1, then, please ng deploy again. Then maybe you can see it reply user account and password not correct, then, please try again do  ng deploy again, if it still stock at Account1, please terminate the terminal and start terminal again then goto step7 to make sure the credential using correct Account2, then goto step9 to git push to see push success then goto step10 do ng deploy again. In my case, I get ng deploy success at this step.

Steps above is not neat as a programmer should do, but It works and save me time before I got through GitHub's CD/CI settings and errors.

@JohannesHoppe Thank you very much. Thanks for your reply. It let me learn CD/CI. Very Good suggest. Thanks.

**Comment by JohannesHoppe** [comment]
> You suggest use CD/CI action script to deploy.
> That did work.

Great. That is the main task of this tool. I don't have the resources to give you guidance on how to set up git on your machine.
