### ISSUE TITLE
index.html could not be copied to 404.html, cli: 1.0.5, angular cli: 14.2.5

### ISSUE THREAD

**Issue by Thiagovasc** [angular-schule/angular-cli-ghpages#163]
I'm trying to update my deploy but it's getting this error: https://prnt.sc/BkmYWK-y6Nj_
The deploy can't find todo-app on dist folder for some reason

**Comment by fmalcher** [comment]
Thanks for your issue report. Most likely, this has nothing to do with this library itself but there's something missing in your configuration. Please directly post a screenshot here and the exact command you used.

**Comment by Thiagovasc** [comment]
I tried:
 * ng deploy --base-href=/Todo-App/
 * ng deploy --base-href=/path/
 * ng deploy --repo=https://github.com/Thiagovasc/Todo-App.git --base-href=/Todo-App/

![image](https://user-images.githubusercontent.com/70722802/212404649-d097ff9d-48bf-4695-a783-516990a6a1cc.png)

**Comment by fmalcher** [comment]
You have to call the command from the root folder, not from `src`. The warning tries to suggest this: "This does not look like an angular-cli project" which is right – the `src` folder does not contain one 😄 

Closing this here, as it's not an error in the library.
