### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by fmalcher** [angular-schule/angular-cli-ghpages#167]
Angular 16 is out, and we are happy to say that this package is compatible with the new Angular without any notable changes.
However, the `ng add` command fails at the moment:

```
$ ng add angular-cli-ghpages
ℹ Using package manager: npm
✔ Found compatible package version: angular-cli-ghpages@0.6.2.
✔ Package information loaded.

The package angular-cli-ghpages@0.6.2 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
NOT SUPPORTED: keyword "id", use "$id" for schema ID
```

This is because the Angular CLI looks for the most compatible version where all peerDependencies are met.
Since we set Angular itself to <= 15 in our peer deps, it will select a very old version.

**As a workaround, please add `@latest` here and ignore the warning:**

```
ng add angular-cli-ghpages@latest
```

This is a very small fix, and we're trying to release a new version in the next couple of days.
PRs are welcome!

**Comment by JohannesHoppe** [comment]
Fixed in latest release, see https://github.com/angular-schule/angular-cli-ghpages/releases/tag/v1.0.6
