### ISSUE TITLE
Deployment fails after upgrading to 2.0

### ISSUE THREAD

**Issue by acieroid** [angular-schule/angular-cli-ghpages#182]
Hi,

We are using angular-cli-ghpages for the deployment of the following project: https://github.com/EveryBoard/EveryBoard
We recently upgraded from angular-cli-ghpages 1.0.7 to 2.0.0-beta.2
However, this has broken the deployment.

We are deploying through GitHub Actions as follows: `npx ng deploy --base-href=/ --repo=https://github.com/EveryBoard/develop --cname=dev.everyboard.org --message="Deployment from action (commit $GITHUB_SHA)" --name some-name --email 'some@email.org'`

And this results in the following error:
```
❌ An error occurred when trying to deploy:
CNAME file could not be created. ENOENT: no such file or directory, open 'dist/everyboard/browser/CNAME'
Error: Process completed with exit code 1.
```
(You can see the full fail build log here if needed: https://github.com/EveryBoard/EveryBoard/actions/runs/8255569790/job/22595989116)

Any idea what might have caused it and how to fix it?

**Comment by acieroid** [comment]
Thanks for the fast answers. Indeed this seems related to the new builder. The answer in #181 was definitely useful. 
Unfortunately, we are hitting some issues when using the new builder, so our solution for now was to downgrade to angular-cli-ghpages 1.0.6.

**Comment by fmalcher** [comment]
You can just use the "dir" option of angular-cli-ghpages to specify the build output directory. It works withe the older browser builder. 🙂
