### ISSUE TITLE
Error on CNAME file creation

### ISSUE THREAD

**Issue by robsonbittencourt** [angular-schule/angular-cli-ghpages#197]
After updating an application from Angular version 15 to version 18.2.9, the ng deploy command started returning the error below.

Command:
`ng deploy --cname=vgcmulticalc.com`

Output:
```
index.html could not be copied to 404.html. Proceeding without it.
❌ An error occurred when trying to deploy:
CNAME file could not be created. ENOENT: no such file or directory, open 'dist/browser/CNAME'
```

My repository:
https://github.com/robsonbittencourt/vgc-multicalc

**Comment by fmalcher** [comment]
Since your dist directory is the root of `dist` without a browser subfolder, you have to configure whoich directory should be deployed. You can either use the CLI arg `--dir` or put the config into your `angular.json` file:

```json
"deploy": {
  "builder": "angular-cli-ghpages:deploy",
  "options": {
    "dir": "dist"
  }
}
```
