### ISSUE TITLE
Updating Github repo with modified build

### ISSUE THREAD

**Issue by ronraney** [angular-schule/angular-cli-ghpages#34]
Hello, I'm very new to Angular 2-5 and still learning Git/Github.

I figured out how to use ng build to deploy an Angular app to Github Pages. It is working but it's still the original version. I have since changed some code, and tried to rebuild and re-deploy. I'm not sure how to update the app, or re-deploy. I can't find much documentation on this subject.

Can anyone point me in the right directions? Once again, I just want to learn how to successfully rebuild and app, and re-deploy to my Github Pages, or "update" the app.

Thanks,
Ron R

**Comment by JohannesHoppe** [comment]
Sorry, but this is not very much related to angular-cli-ghpages! 😉
