### ISSUE TITLE
github "Custom domain" settings are cleared after deployment

### ISSUE THREAD

**Issue by takahser** [angular-schule/angular-cli-ghpages#38]
When using custom domains on github pages, the "custom domain" settings are cleared after building and publishing an angular app. After setting the custom domain in the settings manually again, the page would work, but it would be more convenient, if the custom domain settings would remain unchanged when deploying.

**update**

Found this: https://github.com/tschaub/gh-pages/issues/213

Apparently, the solution is to add a `CNAME` file to the root directory which contains the custom domain in case of manual deployment. So I checked the local `gh-pages` branch which contains that file with the corresponding domain name. However, **the remote** `origin/gh-pages` **branch doesn't contain any CNAME file** for some reason. It seems like its not getting pushed for some reason during deployment.

**Comment by JohannesHoppe** [comment]
Jep. see https://github.com/angular-schule/angular-cli-ghpages/wiki/FAQ#my-cname-file-is-deleted-on-every-publish-specific-to-github-pages-only

When I have some time, I will add the paramter `--cname`

**Comment by takahser** [comment]
lovely! thanks
