### ISSUE TITLE
ngh is an independent package in itself.

### ISSUE THREAD

**Issue by cRAN-cg** [angular-schule/angular-cli-ghpages#39]
I have used this module and it's like super awesome, was curious about the working mechanism of it so I searched for the [`ngh`](https://www.npmjs.com/package/ngh) package. To my surprise, [`ngh`](https://www.npmjs.com/package/ngh) is both an alias to this(`angular-cli-ghpages`) package and a proper command for triggering the [`ngh`](https://www.npmjs.com/package/ngh) module. Also installing both of them causes a possible name conflict.

**Comment by JohannesHoppe** [comment]
Good point. This script can be executed via the command line as `angular-cli-ghpages` or via the alias `ngh` for lazy people like me.

There is absolutely no relationship 
to httpsww.npmjs.com/package/ngh . Installing both globally will not work.

**Comment by JohannesHoppe** [comment]
Nope, it is very common to have a longer package name and a shorter cli command, examples:

* `typescript` --> `tsc`
* `@angular/cli` --> `ng`
* `node-sass` --> `sass`

and so on. Naming collisions are unpreventable, since you can't block "your" bin key in any way on npmjs.com... 😞

**Comment by cRAN-cg** [comment]
Ok, thanks

**Comment by JohannesHoppe** [comment]
I changed my mind and changed to documentation. `ngh` is now highly deprecated, since you might end up using the wrong package.

`npx angular-cli-ghpages` is now the official command.
