### ISSUE TITLE
index.html could not be copied to 404.html. Continuing without an error.

### ISSUE THREAD

**Issue by pratik-bali** [angular-schule/angular-cli-ghpages#41]
`ngh --dir dist/third`
`sudo angular-cli-ghpages --branch gh-pages`
`angular-cli-ghpages`
index.html could not be copied to 404.html. Continuing without an error.
An error occurred!
 Error: Unspecified error (run without silent option for detail)
then i tried
` sudo npm run deploy`
then it says successfully published
with error listed above

**Comment by dyh333** [comment]
+1

**Comment by JohannesHoppe** [comment]
Duplicate of #37, use `--dir` until I figured out an automated detection of the right folder.

**Comment by Atekawere** [comment]
npx angular-cli-ghpages --dir=dist/Git-Search
index.html could not be copied to 404.html. This does not look like an angular-cli project?!
(Hint: are you sure that you have setup the directory correctly?)
Diagnostic info: ENOENT: no such file or directory, stat '/home/victor/Desktop/Git-Search/Git/dist/Git-Search/index.html'
👨🚀 Uploading via git, please wait...
❌ An error occurred when trying to deploy:
ENOENT: no such file or directory, stat '/home/victor/Desktop/Git-Search/Git/dist/Git-Search'
 
Getting this error which i dont understand

**Comment by JohannesHoppe** [comment]
Please use the new `ng deploy` (see README) command which determines the right folder!
