### ISSUE TITLE
i deploy successful, but access wrong.

### ISSUE THREAD

**Issue by littleOStar** [angular-schule/angular-cli-ghpages#43]
1 cmd
```
ng build --prod --base-href "https://littleostar-angular2-learn.github.io/angular2-reddit/"
ngh
```

2 access
https://littleostar-angular2-learn.github.io/angular2-reddit/ 404
https://littleostar-angular2-learn.github.io/angular2-reddit/angular2-reddit/ right page show me

3 branch
gh-pages: use ngh
master: angular build

please help me

**Comment by littleOStar** [comment]
the repository: https://github.com/littleostar-angular2-learn/angular2-reddit

**Comment by fmalcher** [comment]
From Angular CLI 6 the project build are put in a subfolder under `dist`.
This is why you need to explicitely set the deploy directory with the `ngh` command:
```bash
ngh --dir dist/angular2-reddit/
```

As described here:
https://github.com/angular-schule/angular-cli-ghpages/issues/37#issuecomment-388589863

**Comment by littleOStar** [comment]
yeah, it's work!
thanks!
i hope the doc offer more detail. or example.

(GitHub pages seems to be slow to respond)

**Comment by fmalcher** [comment]
I added a section reagarding this topic in the README:
https://github.com/angular-schule/angular-cli-ghpages/commit/98ce574306157723d219cf90dde7b90e991f1b3c
