### ISSUE TITLE
index.html could not be copied to 404.html. Continuing without an error.

### ISSUE THREAD

**Issue by iweb1997** [angular-schule/angular-cli-ghpages#44]
I created a simple app in angular 6 and trying to deploy it on github pages, Successfully run the following command
ng build --prod --base-href "repo url"

But when run ngh command, **Got the error**,

index.html could not be copied to 404.html. Continuing without an error.
(Hint: are you sure that you have setup the --dir parameter correctly?)
{ Error: ENOENT: no such file or directory, lstat 'D:\Programming\Javascript\Angular\my-app\dist\index.html'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'D:\\Programming\\Javascript\\Angular\\my-app\\dist\\index.html' }
*** Successfully published!

**Comment by JohannesHoppe** [comment]
3rd sentence
