### ISSUE TITLE
(node:8040) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by davecar21** [angular-schule/angular-cli-ghpages#48]
Node v10.15.0
NPM v6.4.1
NG 7.2.2

I have be able to push my project in the repository.
Currently trying to publish but this deprecation warning shows and I cannot publish the project.

![image](https://user-images.githubusercontent.com/17526518/51390700-f7d62280-1b6a-11e9-87d1-5130309a9c3a.png)

How to resolve this problem?

**Comment by davecar21** [comment]
forgot to install angular-cli-ghpages in dev dependencies

npm i angular-cli-ghpages --save-dev

"devDependencies": {
   "angular-cli-ghpages": "^0.5.3"
}

**Comment by JohannesHoppe** [comment]
`npx ngh` can result to the wrong npm package, if it wasn't installed before. always use `npx angular-cli-ghpages`. This requires no installation.

**Comment by davecar21** [comment]
I see, if I install angular-cli-ghpages globally then I should use npx angular-cli-ghpages rather than npx ngh?

**Comment by JohannesHoppe** [comment]
No. Npx always works locally. But it can install commands in the fly. In this case it's bad, since there is another package with that Name `ngh`. Ngh ist deprecated and nowhere documented in the latest README.
