### ISSUE TITLE
Angular 7 project doesn't publish on Github - shows only ReadMe file (I've used GitHub Pages)

### ISSUE THREAD

**Issue by itayperry** [angular-schule/angular-cli-ghpages#50]
When I publish Angular projects I usually always do the same thing.. but for some reason it doesn't work anymore. That's exactly what I wrote: (The repo name is movies)

```
git init

git remote add origin <MyGitHubLink>

git add *

git commit -m 'first-commit'

git push -u origin master

ng build --prod --base-href https://itayperry.github.io/movies (from ghpages on github settings)

ngh --dir dist/movies
```

Then I get the message *** Successfully published! but all I see is the README file.

Please help me!!

The repository: https://github.com/itayperry/movies

The published page: https://itayperry.github.io/movies/

**Comment by fmalcher** [comment]
It looks like you forgot the equals sign for the `--dir` argument.
Please try this:

```
ngh --dir=dist/movies
```

**Comment by itayperry** [comment]
Still doesn't work.. it's so weird :( 
It's supposed to be easy lol

**Comment by fmalcher** [comment]
The publishing with `ngh` works correctly, as the build artifacts can be seen here on the `gh-pages` branch. Therefore, this is not related to this project at all, so I will close the issue for now.
Please check the repo setting on GitHub to see which branch is being used for GitHub Pages. It must be `gh-pages` and not `master`.

**Comment by itayperry** [comment]
Omg thanks!! I'm a junior developer.. so I make many mistakes.
This project was for a job interview, and now I can send it to the company thanks to you!!

**Comment by Programazing** [comment]
@itayperry Good luck
