### ISSUE TITLE
Doesn't work for Angular 8

### ISSUE THREAD

**Issue by EmiliaPaz** [angular-schule/angular-cli-ghpages#54]
I tried to deploy a github page using angular-cli-ghpages for the new Angular 8 but it didn't work.

I got these errors in the console:

```
emiliapaz.github.io/:12 GET https://emiliapaz.github.io/agp/polyfills-es2015.e954256595c973372414.js net::ERR_ABORTED 404
emiliapaz.github.io/:9 GET https://emiliapaz.github.io/agp/styles.09e2c710755c8867a460.css net::ERR_ABORTED 404
2emiliapaz.github.io/:12 GET https://emiliapaz.github.io/agp/runtime-es2015.858f8dd898b75fe86926.js net::ERR_ABORTED 404
```

**Comment by fmalcher** [comment]
Can you please provide the exact command you did for publishing? This rather looks like there's something wrong with the base href. Thanks

**Comment by do-kevin** [comment]
Hey there, I may have a problem that's related.

![scripts](https://user-images.githubusercontent.com/40156784/60752815-0b414280-9f7f-11e9-900b-dde2ca2e4957.png)

![problem](https://user-images.githubusercontent.com/40156784/60752816-0d0b0600-9f7f-11e9-8159-ff755a930e99.png)

I get GitHub's 404 page after the "successful" deployment

**Comment by JohannesHoppe** [comment]
Please refer to the readme: https://github.com/angular-schule/angular-cli-ghpages#usage-with-angular-cli-6-or-higher

You must provide the following parameter:
 `--dir=dist/[PROJECTNAME]`
