### ISSUE TITLE
CORS error when requesting dist files

### ISSUE THREAD

**Issue by Badbreaddead** [angular-schule/angular-cli-ghpages#55]
Hello. Thank you for your work!
I am having CORS error:
`Access to script at 'https://USER_NAME.github.io/REPO_NAME/main-es2015.25489881bec059fbf1a6.js' from origin 'https://USER_NAME.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`
And it is all the same for :
`https://USER_NAME.github.io/REPO_NAME/runtime-es2015.858f8dd898b75fe86926.js`
and 
`https://USER_NAME.github.io/REPO_NAME/polyfills-es2015.5728f680576ca47e99fe.js`
Your help is appreciated

**Comment by jinglescode** [comment]
I build with this command:
`ng build --prod --base-href 'https://USERNAME.github.io/REPOSITORY_NAME/' --source-map --build-optimizer`

**Comment by JohannesHoppe** [comment]
Uppercase words must be replaced by real values!

**Comment by akirataguchi115** [comment]
The [documentation](https://angular.io/guide/deployment) suggests using this command:
`ng build --output-path docs --base-href /your_project_name/`
