### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jinglescode** [angular-schule/angular-cli-ghpages#58]
Hi, thanks for developing this, it has been awesome! I'm wondering if server-side rendering (for SEO) is possible for Angular projects hosted on Github Pages?

**Comment by fmalcher** [comment]
Dynamic SSR is not possible with GH Pages, unfortunately. However, static pre-rendering works since you only generate static HTML files at build time for each route.

**Comment by jinglescode** [comment]
Thanks for replying. I assumed the `static pre-rendering` you mentioning is `https://angular.io/guide/universal`? If it is, I will give it a try again, as it has problems building for me just now.

**Comment by fmalcher** [comment]
The thing described in the Universal guide is about dynamic SSR. That means, when the browser requests the site, the server will bootstrap Angular and get the resulting HTML from the DOM on the server. We need Node.js for this.
However, with GH Pages you can't use anything with a server process involved, but just real static HTML files. Thus, the only applicable solution is static pre-rendering. That means, we generate the HTML for each route at build time (!), save it to the file system and just deploy the static HTML files to GH pages. Here's an example: https://github.com/angular-schule/demo-ssr-playground/blob/master/prerender.ts

Closing this issue for now as it is not related to this project.

**Comment by suuf** [comment]
Hello, this is quite an old thread but I think it's the most applicable to my problem. I am trying to index my Angular project on Google's Search Engine with this package through Github Pages. 

Is there any bypass to getting the site to become indexable through any of the package's options at this point in time?

Also, the example link in the above comment doesn't work anymore.

**Comment by fmalcher** [comment]
The answer is conceptually the same as before, actually. 🙂
The question of how search engines interact with the site is beyond the scope of this package. It's not about the deployment itself but about how the app is built.

Even though the Google Bot can actually handle a pure client-side SPA, I'd recommend to use Server-Side Rendering or Pre-Static Rendering to generate static HTML output that can be read by crawlers without actually rendering the application.
The new ESBuild-based application builder (introduced with Angular v17) handles all of this for us. once correctly configured, it's one single `ng build` command to generate static pages.

However, GitHub Pages is just a static web server and not capable of performing dynamic SSR at any point.
The only way that works is to use Static Pre-Rendering.

**Comment by suuf** [comment]
Thank you so much!
