### ISSUE TITLE
Implement an Angular CLI builder

### ISSUE THREAD

**Issue by mgechev** [angular-schule/angular-cli-ghpages#59]
Yesterday I published [`ngx-gh`](https://github.com/mgechev/ngx-gh) which does something quite similar. Today @StephenFluin found `angular-cli-ghpages` and shared it with me.

You're doing a great job! Do you want to work on implementing an Angular CLI builder that will allow invoking the `angular-cli-ghpages` with `ng deploy` (once the command gets in the CLI)? I'll be happy to deprecate `ngx-gh` in favor of `angular-cli-ghpages` once you have tighter CLI integration.

**Comment by JohannesHoppe** [comment]
@mgechev 
Thank you so much, that’s a great idea! We already had something like this in mind, but were afraid of the initial effort.

Am I right assuming that it’s okay if we are using existing code from your project?

**Comment by JohannesHoppe** [comment]
Once you’re here, I have a general question. :slightly_smiling_face:

I was thinking about whether the focus of the project still fits the name. In our projects we use this package to deploy to Heroku (express with SSR), to Azure App Services and much more – all through pushing to git branches via `angular-cli-ghpages`.

What do you think would fit better into the Angular ecosystem?

a) a dedicated package for each job, e.g. `ngx-gh-pages-deploy`, `ngx-heroku-deploy` and `ngx-app-service-deploy`.

b) an entire package, e.g. `ngx-git-deploy` where you can configure the different targets.

If you look at all the issues, many users have trouble setting up a build (e.g. Travis, CircleCi), obtaining the credentials (e.g. generating a GitHub token) and then keeping those credentials safe. That would be the most important task to solve, but it would be the same for all packages.

**Comment by JohannesHoppe** [comment]
@mgechev I have extended `angular-cli-ghpages`  accordingly. Thank you very much for your advice. 👍 Would you mind taking a quick look to see if everything is okay for you?

**Comment by mgechev** [comment]
@JohannesHoppe sorry for the delayed response. Everything looks good! Thanks for preserving the commit history! :) Just deprecated ngx-gh.
