### ISSUE TITLE
The example base HREF for a non-custom domain should be terminated with a slash.

### ISSUE THREAD

**Issue by TrevorKarjanis** [angular-schule/angular-cli-ghpages#62]
Section A of the documentation for the --base-href option that discusses defining a base HREF for non-custom domains provides the following example.
```bash
ng deploy --base-href=/the-repositoryname
```
This example does not work, because the HREF is not terminated with a slash. Without a slash, the "the-repositoryname" segment is not used. The example may need to be revised.
```bash
 ng deploy --base-href=/the-repositoryname/
```

**Comment by JohannesHoppe** [comment]
Thank you for pointing this out! 👍 

You are absolutely right, I will create a new version right after this! 😃
