### ISSUE TITLE
js module disallowed MIME type

### ISSUE THREAD

**Issue by LenaTevar** [angular-schule/angular-cli-ghpages#64]
Hello, I'm following your guide to deploy a github page but I keep getting this error in console in 3 different bundles: 

`Loading module from “https://lenatevar.github.io/runtime-es2015.5bc68c0dd8cf137fbe82.js” was blocked because of a disallowed MIME type (“text/html”).`

This is the repo with the github page address: https://github.com/LenaTevar/LNUCalc/tree/gh-pages.
 
It is an empty Angular basic project, I did not add any code.
I don't now what is wrong, I literally didn't add any code, I just wanted to try out this with the basic angular page.

**Comment by JohannesHoppe** [comment]
Could you please provide the exact command that was executed?

**Comment by fmalcher** [comment]
The base href in your compiled index.html is set to `/`, but your application runs in a subfolder `LNUCalc`.
This is why the application bundles can't be found. GitHub automaticaly serves a 404 html page then which has the `text/html` MIME type.

You need to provide the `--base-href` option accordingly as described [here in the docs](https://github.com/angular-schule/angular-cli-ghpages#--base-href-):

```
ng deploy --base-href=/LNUCalc/
```
