### ISSUE TITLE
No need of a configuration file (angular-cli-ghpages.json)

### ISSUE THREAD

**Issue by dianjuar** [angular-schule/angular-cli-ghpages#67]
You have in your list of TODO's a configuration file to do not write all those parameters...

![image](https://user-images.githubusercontent.com/7026066/63607673-b0989000-c598-11e9-867b-da9c88bf91be.png)

I think there is no necessary because the `options` property in the `angular.json` already has that feature and it works...

Take a look

![image](https://user-images.githubusercontent.com/7026066/63607942-51874b00-c599-11e9-94ee-07d759e38756.png)

And the dry-run says:

![image](https://user-images.githubusercontent.com/7026066/63608085-b2af1e80-c599-11e9-85f4-85ebdf7af2e0.png)

---------

The feature is great but could be donde using something that is already built. What about to write this down in the documentation ?

**Comment by JohannesHoppe** [comment]
You're absolutely right about that! 👍 

And you are already familiar with the subject. Could you imagine creating a PR and improving the README accordingly? An explanation of the configuration via the `angular.json` file would be very helpful! 🙂

**Comment by dianjuar** [comment]
For sure!

Assigne this issue pls

**Comment by JohannesHoppe** [comment]
😀
