### ISSUE TITLE
Auto-completion for angular.json

### ISSUE THREAD

**Issue by JohannesHoppe** [angular-schule/angular-cli-ghpages#69]
@dianjuar wrote in https://github.com/angular-schule/angular-cli-ghpages/pull/68#issuecomment-524897986

> I'm wonder if we can provide a `schema.json` for those options all have all the benefits (auto-completion, validation, descriptions) 🤔

... and this should be possible because that file does exist:
https://github.com/angular-schule/angular-cli-ghpages/blob/eb782e57a838a69b96bacdb1968a3be98683460b/src/builders.json#L6

**Comment by EdricChan03** [comment]
Unfortunately, I don't think it can be done as Angular CLI currently hardcodes the schema for `angular.json` to accept only specific Angular builders. See the [config schema](https://github.com/angular/angular-cli/blob/4630e03209fe06c75315b323b3019418da2c33fa/packages/angular/cli/lib/config/schema.json#L438-L472) for reference.
