### ISSUE TITLE
[feature request] CNAME file for custom domains is replaced

### ISSUE THREAD

**Issue by PascalTemel** [angular-schule/angular-cli-ghpages#7]
If your github pages project is deployed on a custom domain, ngh overwrites this file and it has to be recreated after every push.

**Comment by JohannesHoppe** [comment]
That's by design, it overrides everything.
If it wouldn't do that, all the hashed bundles would stay, too!

You have to put a `CNAME` file into your `dist` folder.
I should start a wiki! :-)

**Comment by PascalTemel** [comment]
It might be intended, but it really seems like bad design. I didnt expect to have to do that since ng gh-pages didnt delete that file either. Maybe its worth discussing this again internally, or rethinking it.

**Comment by JohannesHoppe** [comment]
Yeah, we have to see. I will keep that issue open for a while, to see other peoples opinion on that issue.
The original angular-cli command got too complicated and now it's gone. :smile: My goal is to keep it simple.

What do you think about a `--cname=my.domain` command line option?
Meanwhile, I created a FAQ:
https://github.com/angular-buch/angular-cli-ghpages/wiki/FAQ

**Comment by PascalTemel** [comment]
A command line option would be enough for me.

**Comment by JohannesHoppe** [comment]
That's easy.
The quick way: You send a PR! ;-)
The slower way: I will do that if there is some time!

**Comment by PascalTemel** [comment]
I don't think I have the necessary know-how to do it, but I might look into it sometime.

**Comment by coryshaw1** [comment]
I ended up making an extra build step in my Travis CI config. I added a `copy:cname` script in my package.json, and just called it after `ng build` step.

`"copy:cname": "cp ./CNAME ./dist/CNAME"`

This works fine, but a command line option would be nice!

**Comment by JohannesHoppe** [comment]
I will add this command (--cname=my.domain.org) in v.0.5.1 together with an option to create the `404.html` .

**Comment by alexjlockwood** [comment]
Hi there, just wondering did this make it into v0.5.1?

**Comment by JohannesHoppe** [comment]
No, now it's planned for `0.5.2`.  Shouldn't take much time to implement.

**Comment by JohannesHoppe** [comment]
Shame on me, still not implemented...

**Comment by JaxonWright** [comment]
For windows, I just made an NPM script in my package.json as the following
`"build": "ng build --prod --base-href\"/\"; cp CNAME dist",`

**Comment by beeman** [comment]
Another way to get the CNAME file in place is by creating the file `src/CNAME` and add `CNAME` to the `assets` array in `.angular-cli.json`.

**Comment by JohannesHoppe** [comment]
okokok... i will move this very much up on my free-open-source-work list! 😉

**Comment by silvelo** [comment]
You just can add CNAME to angular-cli.json in assets property, and when build CNAME will be added to dist folder.

**Comment by JaxonWright** [comment]
@beeman wow. I don't know how I didn't think about that

**Comment by bdavies** [comment]
I've submitted a PR (#42) for review to address this Feature Request. Tested locally, any feedback would be welcome.

**Comment by JohannesHoppe** [comment]
Many thanks for the great work! I will take a closer look this weekend! 👍

**Comment by JohannesHoppe** [comment]
v.0.5.3 which adds the `--cname` parameter (PR #42)
many thanks to @bdavies for the PR

**Comment by RajuMandala** [comment]
@beeman Thank you

**Comment by ChrisDinhNZ** [comment]
Good stuff you guys @bdavies @JohannesHoppe
