### ISSUE TITLE
HELP 404 errror

### ISSUE THREAD

**Issue by elledkaye** [angular-schule/angular-cli-ghpages#76]
I get this error 
**```
index.html could not be copied to 404.html. This does not look like an angular-cli project?!
(Hint: are you sure that you have setup the directory correctly?)
Diagnostic info [Error: ENOENT: no such file or directory, stat 'C:\Users\19022630\Desktop\Sweeter-Things\dist\index.html'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\19022630\\Desktop\\Sweeter-Things\\dist\\index.html'
```**

in my angular.json folder my output path = "dist/project1" 

**Under dist folder/project1 folder**
404.html my base href = https://elledkaye.github.io/Sweeter-Things/ 
index.html based href =https://elledkaye.github.io/Sweeter-Things/

I'm wondering if the project folder that's under the dist folder is causing the issue.

I may be having a moment but I am having issues. 

My default branch is set to master.

**Comment by fmalcher** [comment]
Can you please provider your Angular CLI version and the exact command you used?

**Comment by elledkaye** [comment]
Angular version : 8.2.2  and my steps include: 

-installed gh-pages globally 
-github repository already set up 

Ran the following: 
`ng build --prod --base-href="https://elledkaye.github.io/Sweeter-Things"`  
`angular-cli-ghpages --dir=dist/project1

**Comment by fmalcher** [comment]
Please check whether there are some files in the `gh-pages` branch of your repo. If yes, then the problem is most likely with GitHub. It looks like you repo is private. Maybe you didn't enable GitHub Pages for this repo?
Please let us know whether the upload to the `gh-pages` branch worked correctly. Thanks!

**Comment by JohannesHoppe** [comment]
Closed due to inactivity

**Comment by zajanah** [comment]
**I have this problem not solved**

index.html could not be copied to 404.html. This does not look like an angular-cli project?!
(Hint: are you sure that you have setup the directory correctly?)
Diagnostic info: ENOENT: no such file or directory, stat 'E:\Angular Learning\github-followers\dist\index.html'
�‍� Uploading via git, please wait...
❌ An error occurred when trying to deploy:
Unspecified error (run without silent option for detail)

**Comment by fmalcher** [comment]
@zajanah Which command did you use exactly?
From which directory did you try to run the command from?

**Comment by zajanah** [comment]
> @zajanah Which command did you use exactly?
> From which directory did you try to run the command from?

i use$ ngh --dir dist/
and also $ ng
and also $ngh --dir=dist/github-followers

**Comment by fmalcher** [comment]
@zajanah You need to build the project first with `ng build --prod` if you use the command `ngh`.
We recommend to use the deployment builder that can be invoked via `ng deploy` then (with args). It will take care of the build automatically.

**Comment by zajanah** [comment]
> @zajanah You need to build the project first with `ng build --prod` if you use the command `ngh`.
> We recommend to use the deployment builder that can be invoked via `ng deploy` then (with args). It will take care of the build automatically.

yes i do it $ng build --prod --base-href="https://zajanah.github.io/github-followers/"

**Comment by fmalcher** [comment]
@zajanah Please provide a reproduction then, i.e. the repo in question (or a similar one where the same error occurs) and the exact commands we need to run it.
