### ISSUE TITLE
[feature request] add --dir option again

### ISSUE THREAD

**Issue by mscudlik** [angular-schule/angular-cli-ghpages#79]
With Version 0.5.3 there was a `--dir` option to specify the folder that will be uploaded.
This is quite usefull if you want to use angular-cli-ghpages not for the app itself, but for the compodoc generated documentation for example.  Because of the missing option (or is not documented) i currently cannot upgrade.

**Comment by JohannesHoppe** [comment]
I see. With `ng deploy` the directory is determined by the environment (as configured in the file `angular.json`). So there is no need for the `--dir` option any longer for the new deploy builder.

But I made `angular-cli-ghpages` fully backwards-compatible. You can just upgrade and everything should still work, see: https://github.com/angular-schule/angular-cli-ghpages/blob/master/docs/README_standalone.md

Don't worry, we will not remove the "old" standalone option. We internally use it for many different deployment tasks, too.

**Comment by phodal** [comment]
Hi,

I use https://github.com/scullyio/scully to build a SSG work, but it will generate to `dist/static`, so In the future, will the standalone version will still works?  Because `npx angular-cli-ghpages` will use lateset angular-cli-ghpages.

**Comment by d-koppenhagen** [comment]
@phodal you should probably check out the "scully publish" github action: https://github.com/marketplace/actions/scully-publish

**Comment by phodal** [comment]
I had checkout it, but I don't support deploy to another repo. I don't want to deploy `gh-pages` and code in the same repo.

I use [https://github.com/phodal/ledge](https://github.com/phodal/ledge) to development, and use [do](https://github.com/phodal/do) for deploy. But, I will leave issue to it, 😆

**Comment by JohannesHoppe** [comment]
Of course, you can deploy to every remote repository and to every branch. Please refer to the manual! (Options `--repo` and `--branch`)

**Comment by phodal** [comment]
@JohannesHoppe the situation is, If I use scully it will generate code to `dist/static` not the `dist/[project_name]`. So , I change to `npx angular-cli-ghpages` now,  And I just want to confirm it will keep backwards-compatible in future?

**Comment by JohannesHoppe** [comment]
No problem. We use `npx angular-cli-ghpages` for a huge amount internal projects here and deploy all kinds of node.js projects with it. The "old" command will stay, for sure.

But direct support from Scully would be a nice idea. Could you create a new issue and describe the feature as detailled as possible? (A PR would be the very best, of course! 😉)

**Comment by phodal** [comment]
Sorry, it's my fault, Scully support for `outDir`, I just leave it for compare difference.

Thanks guys.
