### ISSUE TITLE
ng add xxx returns "The package that you are trying to add does not support schematics."

### ISSUE THREAD

**Issue by kenmikanmi** [angular-schule/angular-cli-ghpages#80]
# Problem overview
- During setting up my GitHub pages project, `ng add xxx` fails. That says required packages `@angular-devkit/architect` and `@angular-devkit/core` don't support `schematics`.
- `ng deploy --base-href=/webpage/` (`webpage` is a project name initialized by `ng new` command) shows following log without adding any changes in remote repository and GitHub pages:
```bash
➜  webpage git:(master) ✗ ng build --base-href=/webpage/                                              
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {runtime} runtime-es2015.js, runtime-es2015.js.map (runtime) 6.16 kB [entry] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.16 kB [entry] [rendered]
chunk {styles} styles-es2015.js, styles-es2015.js.map (styles) 9.71 kB [initial] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 11 kB [initial] [rendered]
chunk {main} main-es2015.js, main-es2015.js.map (main) 56.3 kB [initial] [rendered]
chunk {main} main-es5.js, main-es5.js.map (main) 58.6 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 637 kB [initial] [rendered]
chunk {vendor} vendor-es2015.js, vendor-es2015.js.map (vendor) 2.35 MB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 2.75 MB [initial] [rendered]
chunk {polyfills} polyfills-es2015.js, polyfills-es2015.js.map (polyfills) 140 kB [initial] [rendered]
Date: 2019-11-05T13:48:42.205Z - Hash: fc6f86b7f9e8f4e03967 - Time: 15304ms
```

# What I did

I followed the install guide described [here](https://www.npmjs.com/package/angular-cli-ghpages) and the command `ng add angular-cli-ghpages` shows:
```bash
➜  webpage git:(master) ng add angular-cli-ghpages
Installing packages for tooling via npm.
npm WARN angular-cli-ghpages@0.6.0 requires a peer of @angular-devkit/architect@>=0.800.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-cli-ghpages@0.6.0 requires a peer of @angular-devkit/core@>=8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-cli-ghpages@0.6.0 requires a peer of @angular-devkit/schematics@>=8.0.0 but none is installed. You must install peer dependencies yourself.

+ angular-cli-ghpages@0.6.0
added 15 packages from 8 contributors and audited 16556 packages in 8.641s
found 0 vulnerabilities

Installed packages for tooling via npm.
UPDATE angular.json (3721 bytes)
```

As it shows three packages are needed, I tried following command:
```bash
➜  webpage git:(master) ✗ ng add @angular-devkit/architect
Skipping installation: Package already installed
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```

It says two packages `@angular-devkit/architect` and `@angular-devkit/core` don't support `@angular-devkit/schematics` and this seems the reason why I fail to deploy my project to GitHub pages (it shows 404 error page).

Could you tell me how these package dependency problem can be solved?

Thanks.

Here's my Angular CLI's version:
```bash
➜  webpage git:(master) ✗ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.0-rc.0
Node: 12.12.0
OS: darwin x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by fmalcher** [comment]
`ng add` is only possible for packages that explicitly support schematics. This is the case for `angular-cli-ghpages` but it's not for `ng add @angular-devkit/architect`. If you need any NPM package that is not compatible with `ng add` you can simply use `npm install` as usual.

However, what's the problem in your case is that you use Angular CLI in the 9.0.0-rc version but angular-cli-ghpages doesn't. It has peer dependencies to Angular 8 because we aim to support stable versions. Once Angular 9 has finally been released we will bump this up to Angular 9 as well, together with the related packages such as `@angular-devkit/architect`.

For you, it should work as usual with no changes, assuming that there were no breaking changes in the Builders API (as far as I know, there were none).

In your first listing above you ran the `ng build` command instead of `ng deploy`. Please try again 😉

**Comment by JohannesHoppe** [comment]
Everything what @fmalcher said was totally right. The "ng add" part went through with some warnings, but everything should be fine. The problems occurred when you followed the warnings (that we can't suppress, unfortunately). We haven't tested angular-cli-ghpages with Angular 9, but chances are high that it will just work (if you are not touching the dependencies)

**Comment by kenmikanmi** [comment]
@fmalcher @JohannesHoppe Thank you for dealing with it. I followed @fmalcher 's advice and now there seems no problems. Thanks a lot.
