### ISSUE TITLE
The css/js resources shows 404

### ISSUE THREAD

**Issue by Mr-Eve** [angular-schule/angular-cli-ghpages#83]
![image](https://user-images.githubusercontent.com/30228406/69205923-505cbe80-0b86-11ea-86ae-98438b540780.png)

Yesterday, I tried to deploy my Angular application , the page shows 404 at the beginning. And I try to reset some settings and it works.

![image](https://user-images.githubusercontent.com/30228406/69206028-91ed6980-0b86-11ea-9d34-911756376271.png)

And now I modify business code and `ng deploy` again, the pages shows blank, the network shows 404(can not find resources). The repository is public , the URL of page is https://qingflow.github.io/sound/

![image](https://user-images.githubusercontent.com/30228406/69206115-c82ae900-0b86-11ea-8b50-82182ba773b5.png)

I switch branch to `gh-pages` (https://github.com/QingFlow/sound/tree/gh-pages), all files what the network need are exist. Then I am confused, why it shows 404? How can I solve it ?

**Comment by Mr-Eve** [comment]
I know how to solve it. Use command `ng deploy --base-href="./"`

**Comment by fmalcher** [comment]
Right! If you use the Angular app in a sub folder instead of in the web root you need to set the base href accordingly. You used a relative path now, which is fine. An absolute path would also be possible:

```
ng deploy --base-href=/sound/
```
