### ISSUE TITLE
Failed publish Angular site

### ISSUE THREAD

**Issue by tomertro** [angular-schule/angular-cli-ghpages#84]
I successfully run those commands:

ng build --prod --output-path dist/my-portfoilo --base-href "https://tomertro.github.io/my-portfoilo"
ngh --dir dist/my-portfoilo

On my page i get 404 errors.
https://tomertro.github.io/MyRepository/my-portfoilo/

What do i missed here?
Do I need upload the dist folder?

**Comment by fmalcher** [comment]
Your sub folder is `MyRepository/my-portfoilo/` and you need to set the base href accordingly.
I'd rather recommend a path without host:

```
ng build --prod --output-path dist/my-portfoilo --base-href=/MyRepository/my-portfoilo/
```

**Comment by JohannesHoppe** [comment]
But generally I would recommend to use the new `ng deploy` command. This compiles and deploys for you.

**Comment by tomertro** [comment]
I run the following commands:

ng build --prod --output-path dist/my-portfoilo --base-href "https://tomertro.github.io/MyRepository/my-portfoilo"
ngh --dir dist/my-portfoilo

https://tomertro.github.io/MyRepository/my-portfoilo/
results with errors:

Failed to load resource: the server responded with a status of 404 ()


![PageErrors](https://user-images.githubusercontent.com/42818974/69355595-bc284f80-0c8a-11ea-92f7-4542a78eebe1.PNG)
