### ISSUE TITLE
"index.html could not be copied to 404.html." on ng deploy

### ISSUE THREAD

**Issue by yodigi7** [angular-schule/angular-cli-ghpages#86]
Tried to use the `ng deploy` however it gave the above error. Also `ng build --base-href=/path/ &&  ngh` fails. 

Looking at https://github.com/angular-schule/angular-cli-ghpages/issues/37 I changed the build output dir to be `dist` rather than the `dist/[PROJECTNAME]` default. This caused the `ng build --base-href=/path/ &&  ngh` to succeed however `ng deploy` still fails.

**Comment by JohannesHoppe** [comment]
You are mixing the old command line syntax and the new "ng deploy" syntax.

The old command line syntax requires a build by you, it **only deploys**:

```bash
ng build --base-href=/path/
npx angular-cli-ghpages [OTHER OPTIONS]
```

The new "ng deploy" syntax **builds and deploys**. Therefore only in the new syntax the `--base-href` option is available:

```bash
ng deploy  --base-href=/path/ [OTHER OPTIONS]
```
