### ISSUE TITLE
[question] deploy a pre-rendered build

### ISSUE THREAD

**Issue by edbzn** [angular-schule/angular-cli-ghpages#92]
Hi, 

I'm wondering if there is a possibility to deploy using the new prerender builders available in the v9? I found nothing about it in the documentation.

For now I'm using the following command `ng run my-app:prerender --routes` along with a deploy script that use the `gh-pages` package.

Thanks.

**Comment by JohannesHoppe** [comment]
Have you tried to build it manually and then execute the deployment without a build?

```
ng deploy --no-build
```
