### ISSUE TITLE
Cannot deploy js/css although I set base href 

### ISSUE THREAD

**Issue by ttpro1995** [angular-schule/angular-cli-ghpages#97]
My site should be here:[https://ttpro1995.github.io/nebular-angular-playground/]( https://ttpro1995.github.io/nebular-angular-playground/)

Command I run

`ng deploy --base-href="/nebular-angular-playground/"`

The index.html after deploy

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>NebularAgain</title>
  <base href="/"> <!--target self to prevent open new tab-->
  <base target="_self" href="/nebular-angular-playground/">  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.b066b5d58069a9db2b1e.css"></head>
<body>
  <app-root></app-root>
<script src="runtime-es2015.c5fa8325f89fc516600b.js" type="module"></script><script src="runtime-es5.c5fa8325f89fc516600b.js" nomodule defer></script><script src="polyfills-es5.3e8196928d184a6e5319.js" nomodule defer></script><script src="polyfills-es2015.5b10b8fd823b6392f1fd.js" type="module"></script><script src="main-es2015.84063080c214d5e31d78.js" type="module"></script><script src="main-es5.84063080c214d5e31d78.js" nomodule defer></script></body>
</html>
```

However, the site show blank. Error from web console: 

`Failed to load resource: the server responded with a status of 404 ()`

![alt text](https://i.imgur.com/uhnkp8X.png)

Look like the href does not do it job, as my browser try to fetch resource from 
[https://ttpro1995.github.io/styles.b066b5d58069a9db2b1e.css](https://ttpro1995.github.io/styles.b066b5d58069a9db2b1e.css) and so on

**Comment by d-koppenhagen** [comment]
I think this issue can be closed as you managed to fix it here https://github.com/ttpro1995/nebular-angular-playground/commit/26beccb945861091533f607fc3e13d7b8e3e984f don't you?

**Comment by JohannesHoppe** [comment]
He used the very old deprecated API (`ngh` is the name of another npm package!). If you want to use the standalone version, please execute it like this. Npx will install temperately angular-cli-ghpages for you automatically.

```
ng build --prod --base-href "nebular-angular-playground"
npx angular-cli-ghpages --message="First deploy"
```

But generally, I would try to fix the issue and use the recommended `ng deploy` command.
Please double check the index.html and don't manipulate the base-href. A clean index.html looks like this:

```
<head>
  <meta charset="utf-8">
  <title>Title</title>
  <base href="/">
``` 

In the given example the `<base href="/">` was still the same, so I guess the html-comment or something else broken the replacing.
Then this command should work:

```
ng deploy --base-href=/nebular-angular-playground/
```

**Comment by ttpro1995** [comment]
> I think this issue can be closed as you managed to fix it here [ttpro1995/nebular-angular-playground@26beccb](https://github.com/ttpro1995/nebular-angular-playground/commit/26beccb945861091533f607fc3e13d7b8e3e984f) don't you?

Oh, I have 2 line 

```
  <base href="/">
  <base target="_self">	
```

So, `ng deploy` only change the second line while still keep first line into this. So, the base "/" still in effect. 

```
<base href="/">
<base target="_self" href="/my_base_href/">	
```

So, I have to delete first base tag. It should only contain 1 base tag only.

` <base target="_self" href="/">`
